services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: ./
      dockerfile: ./Dockerfile
    # Запускаем тестовый сервер
    command: uvicorn main:app --host 0.0.0.0
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=gamedb
    ports:
      - 5433:5432

volumes:
  postgres_data: